name: Integration tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: ["checks_requested"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install lint dependencies
        run: sudo apt install -y yamllint aspell pre-commit
      - name: "Clone Repository"
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run linters
        run: make lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/testdeps
      - name: Install integration test env
        run: |
          sudo apt update
          sudo apt install -y python3-pytest golang

      - name: Run integration tests via pytest
        run: |
          # use "-s" for now for easier debugging
          sudo pytest -s -v
